[tool.briefcase]
project_name = "Text Twist"
bundle = "martirez.derrynjoi.personalproject"
version = "0.0.1"
url = "https://personalproject.derrynjoi.martirez/texttwist"
license = "MIT license"
author = 'Derryn Joi Martirez'
author_email = "derrynjm@gmail.com"

[tool.briefcase.app.texttwist]
formal_name = "Text Twist"
description = "game based on text twist"
icon = "src/texttwist/resources/texttwist"
sources = ['src/texttwist']
requires = [
]


[tool.briefcase.app.texttwist.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.texttwist.linux]
requires = [
    'toga-gtk>=0.3.0.dev34',
]

[tool.briefcase.app.texttwist.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.texttwist.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.texttwist.windows]
requires = [
    'toga-winforms>=0.3.0.dev34',
]

# Mobile deployments
[tool.briefcase.app.texttwist.iOS]
requires = [
    'toga-iOS>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.texttwist.android]
requires = [
    'toga-android>=0.3.0.dev34'
]
